name: Deploy tag to DockerHub
on: 
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Maven
        run: ./mvnw clean package
      - name: Docker compose and Deploy
        env:
          DEPLOY_SERVER_ADDRESS: ${{ secrets.DEPLOY_SERVER_ADDRESS }}
          DEPLOY_SERVER_KEY: ${{ secrets.DEPLOY_SERVER_KEY }}
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${DEPLOY_SERVER_KEY}"
          docker-compose -H "${DEPLOY_SERVER_ADDRESS}" up -d