name: Deploy tag to DockerHub
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Build the image
      run: |
        docker buildx build \
          --tag bladetitan/mamba-backend:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .